/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#4a6600',
        'primary-dim': '#00d4ec',
        'outline-variant': '#424853',
        'on-primary-fixed': '#003840',
        'on-error-container': '#ffa8a3',
        'surface-container-low': '#0c141e',
        'secondary-fixed-dim': '#cabaff',
        error: '#ff716c',
        'on-surface': '#e8eefc',
        tertiary: '#e9ffba',
        'tertiary-fixed': '#bafd00',
        'on-background': '#e8eefc',
        'surface-container-highest': '#1d2634',
        'surface-tint': '#81ecff',
        'primary-fixed-dim': '#00d4ec',
        'on-tertiary-fixed': '#344a00',
        'tertiary-container': '#bafd00',
        'on-secondary-fixed': '#3b00a0',
        outline: '#6f7682',
        surface: '#080f18',
        secondary: '#a68cff',
        'on-secondary-container': '#e4daff',
        'on-error': '#490006',
        'tertiary-fixed-dim': '#afee00',
        'on-tertiary-fixed-variant': '#4b6800',
        'on-tertiary-container': '#435d00',
        'on-primary': '#005762',
        background: '#080f18',
        'surface-bright': '#222d3b',
        'error-container': '#9f0519',
        'primary-container': '#00e3fd',
        'on-primary-fixed-variant': '#005762',
        'on-surface-variant': '#a5abb8',
        'tertiary-dim': '#afee00',
        'surface-variant': '#1d2634',
        'surface-container': '#121a25',
        'secondary-container': '#591adc',
        'error-dim': '#d7383b',
        'on-secondary': '#25006b',
        'surface-container-high': '#17202c',
        'inverse-primary': '#006976',
        'surface-dim': '#080f18',
        'inverse-surface': '#f8f9ff',
        'secondary-fixed': '#d8caff',
        'on-secondary-fixed-variant': '#591bdc',
        'on-primary-container': '#004d57',
        'inverse-on-surface': '#4f5561',
        'surface-container-lowest': '#000000',
        'primary-fixed': '#00e3fd',
        primary: '#81ecff',
        'secondary-dim': '#7e51ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      gridTemplateColumns: {
        18: 'repeat(18, minmax(0, 1fr))',
        15: 'repeat(15, minmax(0, 1fr))',
      },
      gridColumn: {
        'span-18': 'span 18 / span 18',
        'span-15': 'span 15 / span 15',
      },
      gridColumnStart: {
        13: '13',
        14: '14',
        15: '15',
        16: '16',
        17: '17',
        18: '18',
      },
      gridRowStart: {
        8: '8',
        9: '9',
        10: '10',
      },
    },
  },
  plugins: [],
};
